[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmd = "pnpm install --frozen-lockfile"

[phases.build]
cmd = "cd packages/app && pnpm run build"

[start]
cmd = "cd packages/app && node build"

[variables]
NODE_ENV = "production"
