[phases.setup]
nixPkgs = ["nodejs_20", "pnpm_8"]

# [phases.install]
# cmd = """
  # set -e
  # echo 'starting install phase'
  # npm install -g corepack
  # corepack enable
  # corepack prepare pnpm@8.15.9 --activate
  # pnpm install --frozen-lockfile
  # echo 'finished install phase'
# """

# [phases.build]
# cmd = """
  # set -e
  # echo 'starting build phase'
  # cd packages/client
  # echo 'in packages/client'
  # pnpm run build 
  # echo 'finished build phase'
# """

# [start]
# cmd = """
  # set -e
  # echo 'start' 
  # cd packages/client
  # echo 'in packages/client'
  # node build/index.js
# """

[variables]
NODE_ENV = "production"
