[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmd = "echo 'starting install phase' && pnpm install --frozen-lockfile && echo 'finished install phase'"

[phases.build]
cmd = "echo 'starting build phase' && cd packages/client && echo 'in packages/client' && pnpm run build && echo 'finished build phase'"

[start]
cmd = "echo 'start' && cd packages/client && echo 'in packages/client' && node build/index.js"

[variables]
NODE_ENV = "production"
