[phases.setup]
nixPkgs = ["nodejs", "pnpm"]
aptPkgs = []

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node build"

[variables]
NODE_ENV = "production"
